apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: cicd-project7-deployment
spec:
  selector:
    matchLabels:
      app: cicd-project7
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: cicd-project7
    spec:
      containers:
        - name: cicd-project7
          image: madeep2669/cicd-project7:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: cicd-project7-ssvc
spec:
  selector:
    app: cicd-project7
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: LoadBalancer # type of the service.
